### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by Firues** [utgwkk/askfm.py#21]
Dear utgwkk.
Why is it not working? Or just me?
I used the code from the example and returns nothing.
```
import askfm
crawler = askfm.Crawler('ezoeryou')

for pair in crawler.crawl():
  print(pair.question, '->', pair.answer)
```
Thank you!

**Comment by utgwkk** [comment]
@Firues because of the DOM structures' change in ask.fm . 
Now it is fixed on the latest version. Thanks!
